import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme: "dark",
    }}>
<html lang="en" className="dark"
                    style={{'colorScheme':"dark"}} >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
        
        {/* header */}
        <Header/>
        <main className="min-h-screen">{children}</main>
        <footer className="bg-muted/50 py-5">
          <div className="container mx-auto text-center text-gray-200">
            <p>Made with ❤️ by Garima</p>
          </div>
        </footer>
        
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
